using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeenieViewer.Enums
{
    public enum CreatureType : uint
    {
        Invalid,
        Olthoi,
        Banderling,
        Drudge,
        Mosswart,
        Lugian,
        Tumerok,
        Mite,
        Tusker,
        PhyntosWasp,
        Rat,
        Auroch,
        Cow,
        Golem,
        Undead,
        Gromnie,
        Reedshark,
        Armoredillo,
        Fae,
        Virindi,
        Wisp,
        Knathtead,
        Shadow,
        Mattekar,
        Mumiyah,
        Rabbit,
        Sclavus,
        ShallowsShark,
        Monouga,
        Zefir,
        Skeleton,
        Human,
        Shreth,
        Chittick,
        Moarsman,
        OlthoiLarvae,
        Slithis,
        Deru,
        FireElemental,
        Snowman,
        Unknown,
        Bunny,
        LightningElemental,
        Rockslide,
        Grievver,
        Niffis,
        Ursuin,
        Crystal,
        HollowMinion,
        Scarecrow,
        Idol,
        Empyrean,
        Hopeslayer,
        Doll,
        Marionette,
        Carenzi,
        Siraluun,
        AunTumerok,
        HeaTumerok,
        Simulacrum,
        AcidElemental,
        FrostElemental,
        Elemental,
        Statue,
        Wall,
        AlteredHuman,
        Device,
        Harbinger,
        DarkSarcophagus,
        Chicken,
        GotrokLugian,
        Margul,
        BleachedRabbit,
        NastyRabbit,
        GrimacingRabbit,
        Burun,
        Target,
        Ghost,
        Fiun,
        Eater,
        Penguin,
        Ruschk,
        Thrungus,
        ViamontianKnight,
        Remoran,
        Swarm,
        Moar,
        EnchantedArms,
        Sleech,
        Mukkir,
        Merwart,
        Food,
        ParadoxOlthoi,
        Harvest,
        Energy,
        Apparition,
        Aerbax,
        Touched,
        BlightedMoarsman,
        GearKnight,
        Gurog,
        Anekshay
    }

    public static class CreatureExtensions
    {
        public static string ToSentence(this CreatureType creatureType)
        {
            return new string(creatureType.ToString().ToCharArray().SelectMany((c, i) => i > 0 && char.IsUpper(c) ? new char[] { ' ', c } : new char[] { c }).ToArray());
        }

    }
}
