using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeenieViewer.Appraisal
{
    partial class ItemExamine
    {
        string GetTitle(int titleId)
        {
            switch (titleId){
                case 0: return "Unknown";
                case 1: return "Adventurer";
                case 2: return "Archer";
                case 3: return "Blademaster";
                case 4: return "Enchanter";
                case 5: return "Life Mage";
                case 6: return "Sorcerer";
                case 7: return "Vagabond";
                case 8: return "Warrior";
                case 9: return "Bow Hunter";
                case 10: return "Life Caster";
                case 11: return "Soldier";
                case 12: return "Swashbuckler";
                case 13: return "War Mage";
                case 14: return "Wayfarer";
                case 15: return "Abhorrent Warrior";
                case 16: return "Alchemist";
                case 17: return "Annihilator";
                case 18: return "Apothecary";
                case 19: return "Arctic Adventurer";
                case 20: return "Arctic Mattekar Annihilator";
                case 21: return "Artifex";
                case 22: return "Axe Warrior";
                case 23: return "Ballisteer";
                case 24: return "Bane of the Remoran";
                case 25: return "Blood Shreth Butcher";
                case 26: return "Bloodletter";
                case 27: return "Broodu Killer";
                case 28: return "Browerk Killer";
                case 29: return "Bug Butcher";
                case 30: return "Bugstomper";
                case 31: return "Bunny Master";
                case 32: return "Carenzi Slayer";
                case 33: return "Chain Breaker";
                case 34: return "Champion of Dereth";
                case 35: return "Champion of Sanamar";
                case 36: return "Champion of Silyun";
                case 37: return "Chef";
                case 38: return "Creature Adept";
                case 39: return "Dagger Fighter";
                case 40: return "Deadeye";
                case 41: return "Deathcap Defeater";
                case 42: return "Defender of Dereth";
                case 43: return "Deliverer";
                case 44: return "Diplomat";
                case 45: return "Dire Mattekar Dispatcher";
                case 46: return "Duelist";
                case 47: return "Ebon Gromnie Eradicator";
                case 48: return "Engorged Scourge";
                case 49: return "Evoker";
                case 50: return "Explorer";
                case 51: return "Exterminator";
                case 52: return "Fisherman";
                case 53: return "Fletcher";
                case 54: return "Floeshark Flogger";
                case 55: return "Friend of Sanamar";
                case 56: return "Friend of Silyun";
                case 57: return "Gaerlan Slayer";
                case 58: return "Gardener Weeder";
                case 59: return "Glenden Wood Knight";
                case 60: return "Glenden Wood Militia";
                case 61: return "Golden God";
                case 62: return "Grave Robber";
                case 63: return "Guardian of Dereth";
                case 64: return "Gumshoe";
                case 65: return "Guppy Master";
                case 66: return "Heart Ripper";
                case 67: return "Hero of Dereth";
                case 68: return "Hero of Sanamar";
                case 69: return "Hero of Silyun";
                case 70: return "Honorary Snowman";
                case 71: return "Honorary Windreave";
                case 72: return "Hunter";
                case 73: return "Impaler";
                case 74: return "Insatiable Slayer";
                case 75: return "Invader's Bane";
                case 76: return "Iron Chef";
                case 77: return "Iron-Spined Chittick Immolator";
                case 78: return "Item Adept";
                case 79: return "Keeper of Dereth";
                case 80: return "Keerik Killer";
                case 81: return "Kingslayer";
                case 82: return "Kiree Killer";
                case 83: return "K'nath An'dras Assassinator";
                case 84: return "Lakeman";
                case 85: return "Life Adept";
                case 86: return "Lightbringer";
                case 87: return "Mace Warrior";
                case 88: return "Man-At-Arms Thrasher";
                case 89: return "Master Fletcher";
                case 90: return "Master of Slaughter";
                case 91: return "Master of Staves";
                case 92: return "Miner";
                case 93: return "Moarsman Defiler";
                case 94: return "Morale Smasher";
                case 95: return "Mosswart Worshipper Whipper";
                case 96: return "Mottled Carenzi Mauler";
                case 97: return "Mud Slinger";
                case 98: return "Naughty Skeleton Snuffer";
                case 99: return "Olthoi Ripper Reducer";
                case 100: return "Paragon of Death";
                case 101: return "Philanthropist";
                case 102: return "Plate Armoredillo Punisher";
                case 103: return "Platinum Prowler";
                case 104: return "Polar Ursuin Pounder";
                case 105: return "Polardillo Pummeler";
                case 106: return "Pond Scum";
                case 107: return "Pro Fisherman";
                case 108: return "Projectilist";
                case 109: return "Pugilist";
                case 110: return "Queenslayer";
                case 111: return "Ravenous Killer";
                case 112: return "Red Fury";
                case 113: return "Reeshan Killer";
                case 114: return "Rehir Killer";
                case 115: return "Repugnant Eater Ripper";
                case 116: return "Resistance Fighter";
                case 117: return "Resistance Recruit";
                case 118: return "Servant of The Deep";
                case 119: return "Sezzherei Slayer";
                case 120: return "Shadow Stalker";
                case 121: return "Shallows Shark Nemesis";
                case 122: return "Sharpshooter";
                case 123: return "Shellfish Hater";
                case 124: return "Shield of Glenden";
                case 125: return "Shredder";
                case 126: return "Silver Serf";
                case 127: return "Siraluun Slasher";
                case 128: return "Skipper";
                case 129: return "Skullcrusher";
                case 130: return "Skullsplitter";
                case 131: return "Slicer";
                case 132: return "Sniper";
                case 133: return "Soldier Slaughterer";
                case 134: return "Spear Warrior";
                case 135: return "Spring Cleaner";
                case 136: return "Staff Warrior";
                case 137: return "Stonebreaker";
                case 138: return "Sureshot";
                case 139: return "Swordfighter";
                case 140: return "Theurgist";
                case 141: return "Thrungus Reaper";
                case 142: return "Timberman";
                case 143: return "Tracker";
                case 144: return "Trapper";
                case 145: return "Tukora Lieutenant Trouncer";
                case 146: return "Unarmed Brawler";
                case 147: return "Violator Grievver Vetoer";
                case 148: return "Voracious Flayer";
                case 149: return "Voracious Hunter";
                case 150: return "War Adept";
                case 151: return "Warden of Dereth";
                case 152: return "Warlock";
                case 153: return "Warlord of Dereth";
                case 154: return "Warrior Vanquisher";
                case 155: return "Wicked Skeleton Walloper";
                case 156: return "Windreave Stalker";
                case 157: return "Worker Obliterator";
                case 158: return "Dryreach Militia";
                case 159: return "Honorary Shadow Hunter";
                case 160: return "Perforated Knight";
                case 162: return "Pest Control";
                case 163: return "Rat Reaper";
                case 164: return "Nymph Maniac";
                case 165: return "$imiu$";
                case 166: return "2nd Place Lore- Quiz Night";
                case 167: return "AC Veteran";
                case 168: return "Ain't afraid of no ghost!";
                case 169: return "Ain't afraid of no ghost";
                case 170: return "Ain't afraid of no ghost..mwahaha!";
                case 171: return "Ankle Biter";
                case 172: return "Annoying Furry Talking Animal";
                case 173: return "Archer Assassin";
                case 174: return "Archmage";
                case 175: return "Asheron's Call God";
                case 176: return "Avatar of Kain";
                case 177: return "Azure Assailant";
                case 178: return "Baby Bunny Master";
                case 179: return "Baron Oddity";
                case 180: return "Beginning of the End";
                case 181: return "Best Melee in DT";
                case 182: return "Big Block";
                case 183: return "Big Rocx";
                case 184: return "Blood";
                case 185: return "Bounty Hunter";
                case 186: return "British Tootsie";
                case 187: return "Bug Bait";
                case 188: return "Bunny Killer";
                case 189: return "Carebear Stare";
                case 190: return "Certified Ganksta";
                case 191: return "Chicken Nugget";
                case 192: return "Chicken Select";
                case 193: return "Chimaera's Champion";
                case 194: return "Co-Monarch of TheChosen";
                case 195: return "Containment Unit";
                case 196: return "Coolest Title Ever!";
                case 197: return "Corrosive Soul";
                case 198: return "Cow Killer";
                case 199: return "Cowboy";
                case 200: return "Crystal Lord King";
                case 201: return "Cuddly Kitten >^..^<";
                case 202: return "Curmudgeon's Friend";
                case 203: return "Cursed Adventurer";
                case 204: return "Dagger Master";
                case 205: return "Dark Sword Lady";
                case 206: return "Darktides Finest";
                case 207: return "Darktides Most Wanted";
                case 208: return "Dead Meat";
                case 209: return "Deadly Eggburt";
                case 210: return "Death by Default";
                case 211: return "Death by Pumpkin";
                case 212: return "Death by Sappho";
                case 213: return "Death Specialist";
                case 214: return "Defender of Mr. P";
                case 215: return "Dereth's Gladiator";
                case 216: return "Dereth's Master Dodger";
                case 217: return "Dev Evader";
                case 218: return "Dev Killer";
                case 219: return "Dev Slayer";
                case 220: return "Double Fashion King";
                case 221: return "Double Golem Killer";
                case 222: return "Double Survival Champion";
                case 223: return "Dude of DOOM!";
                case 224: return "Ecto Cooler";
                case 225: return "Ecto-Cooler";
                case 226: return "Envoy Slayer";
                case 227: return "Escapee Killer";
                case 228: return "Evil Toothfairy";
                case 229: return "Fancy Title";
                case 230: return "Fashion King";
                case 231: return "Fashion Penguin King";
                case 232: return "Fashion Queen";
                case 233: return "Fashion Victim";
                case 234: return "Fearless Fighter";
                case 235: return "Flag Boy";
                case 236: return "Frelorn Slayer";
                case 237: return "Friend to Mr. P";
                case 238: return "Gangsta Style";
                case 239: return "Gangster";
                case 240: return "Ghostbuster";
                case 241: return "Gimp";
                case 242: return "Gimp Goddess";
                case 243: return "Gimpy Mage of Might";
                case 244: return "Gladiator Champion";
                case 245: return "Glowing Archer";
                case 246: return "God of the Swordsman";
                case 247: return "Golem Killer";
                case 248: return "Golem Slayer";
                case 249: return "Great Pookie Slayer";
                case 250: return "Guardian Angel";
                case 251: return "Guardian of Arwic";
                case 252: return "Hamster Herder";
                case 253: return "Hamster Vitae";
                case 254: return "Have Bunnie's Will Travel";
                case 255: return "Have Trike Will Babble";
                case 256: return "Hide and Seek Specialist";
                case 257: return "Hollywood Bud";
                case 258: return "Holtburg Survival Champion";
                case 259: return "Holtburg's Survivor Champion";
                case 260: return "Honorary Pink Eep";
                case 261: return "Hungry Hungry Hippo";
                case 262: return "Husband of Lynnie";
                case 263: return "Husbands Healer";
                case 264: return "I am Big []D [] []\\/[] []D [] []\\[]";
                case 265: return "I liked dying!";
                case 266: return "Jessica <3";
                case 267: return "King of all that is Pumpkin";
                case 268: return "King of Caul";
                case 269: return "King of Darktide";
                case 270: return "King of Pierce Diggys";
                case 271: return "Knight Rider";
                case 272: return "Lady of the Four Towers";
                case 273: return "Lange Gang";
                case 274: return "Level Master";
                case 275: return "Leviathan";
                case 276: return "Leviathan Slayer";
                case 277: return "Libe Events Manager";
                case 278: return "Life Preserver";
                case 279: return "Live Event Coordinator";
                case 280: return "Live Events Manager";
                case 281: return "Live Op Coordinator";
                case 282: return "Lore- 2nd Place";
                case 283: return "Lore 2nd Place Quiz Night";
                case 284: return "Lore Champion - Quiz Night";
                case 285: return "Lore Champion Quiz Night";
                case 286: return "Lore Master";
                case 287: return "{{keepspaces}}Lore Master Quiz Night";
                case 288: return "Lore Master - Quiz Night";
                case 289: return "Lore Master 2nd Place";
                case 290: return "Lore Master of Staves";
                case 291: return "Lots of Vitae";
                case 292: return "Lucky Lady";
                case 293: return "Mad Cow Slayer";
                case 294: return "Mages Assitant";
                case 295: return "Master Tinkerer";
                case 296: return "Mayor of Ayan Baqur";
                case 297: return "Minty Fresh";
                case 298: return "Misunderstood Pengy";
                case 299: return "Mom";
                case 300: return "Mommy Pengy";
                case 301: return "Mosswart Ally";
                case 302: return "Mr. Nice Guy";
                case 303: return "Murderer";
                case 304: return "Murderer !";
                case 305: return "Newby Title";
                case 306: return "Nice Blue Lady";
                case 307: return "Number one draft pick";
                case 308: return "Old School";
                case 309: return "Paradox Slayer";
                case 310: return "Patron Saint of the Lifestone";
                case 311: return "Peacebear";
                case 312: return "Penguin Killer";
                case 313: return "Pig Farmer";
                case 314: return "Pink Bunny Killer";
                case 315: return "Pink Bunny Master";
                case 316: return "Pink Goddess";
                case 317: return "Pink Lady";
                case 318: return "PK Queen";
                case 319: return "Playa Killa King";
                case 320: return "Pokemon Slayer";
                case 321: return "Pretty Pumpkin";
                case 322: return "Prisoner";
                case 323: return "Protector of the Cheese";
                case 324: return "Proton Pack";
                case 325: return "Pumpkin Slayer";
                case 326: return "Pumpkin Stalker";
                case 327: return "Purple Pengy";
                case 328: return "Pwner of Newbs";
                case 329: return "Queen of Brats";
                case 330: return "Queens Crafter";
                case 331: return "Queen's Crafter";
                case 332: return "Queen's Pack Rat";
                case 333: return "Queen's Packrat";
                case 334: return "Queen's Tinker";
                case 335: return "Rawr!";
                case 336: return "Rayne's Mage Pet";
                case 337: return "Reggae Renegade";
                case 338: return "Ring Bearer";
                case 339: return "Ring ring ring.....Bananaphone";
                case 340: return "Road Kill";
                case 341: return "Rolling Death Destroyer";
                case 342: return "Royal Chef";
                case 343: return "Royal Cook";
                case 344: return "Rugged";
                case 345: return "Sanitation Engineer";
                case 346: return "Scarecrow Slayer";
                case 347: return "Scary Pumkpkin Dominator";
                case 348: return "Scary Pumpkin Slayer";
                case 349: return "Sentinal";
                case 350: return "Sentry";
                case 351: return "Shadow Child";
                case 352: return "Shadow Hunter";
                case 353: return "Shadow Slayer";
                case 354: return "Slayer of the Great Pookie";
                case 355: return "Slimer";
                case 356: return "Snazzy Dresser";
                case 357: return "Soul Man";
                case 358: return "Spooky Title";
                case 359: return "Staff Masta";
                case 360: return "Staypuffed Mallow Girl";
                case 361: return "Super Gimped Adventurer";
                case 362: return "Supercalifragilisticexpialidocious";
                case 363: return "Superman";
                case 364: return "Survivor Champion";
                case 365: return "Sword Scholar";
                case 366: return "Teh Newb";
                case 367: return "Teh Saint";
                case 368: return "Testing Guy";
                case 369: return "The Bait";
                case 370: return "The Chosen King";
                case 371: return "The Come Back Kid";
                case 372: return "The Forgotten";
                case 373: return "The Gimped";
                case 374: return "The Great and Powerful";
                case 375: return "The Half-Fox";
                case 376: return "The Noob";
                case 377: return "The Purple Fez";
                case 378: return "The Pwnerer";
                case 379: return "The Unknown Pk";
                case 380: return "Thunder Chicken Slayer";
                case 381: return "TM Killer";
                case 382: return "Tough Guy";
                case 383: return "Tradesman of Auberean";
                case 384: return "Treasure Hunter";
                case 385: return "Tremendous Monouga Master";
                case 386: return "Triple Golem Killer";
                case 387: return "Turbine Slayer";
                case 388: return "Twins of Terror";
                case 389: return "Uberest Noob on Frostfell";
                case 390: return "Underworld-Thugg";
                case 391: return "Viamontian Slayer";
                case 392: return "Vitae King";
                case 393: return "Vitae Vixen";
                case 394: return "Vixen of Vitae";
                case 395: return "Wabbit Bait";
                case 396: return "Wabbit Killer";
                case 397: return "Wandering Fool";
                case 398: return "Warden's Assistant";
                case 399: return "Wardens Thug";
                case 400: return "Wimp";
                case 401: return "Wolfpack Crafter";
                case 402: return "Wonder Woman";
                case 403: return "Ya got served";
                case 404: return "GIMP";
                case 405: return "Wardens Assistant";
                case 406: return "Supreme Bunny Master";
                case 407: return "Guardian of the Dark";
                case 408: return "April's Fool";
                case 409: return "Ulgrim's Eep";
                case 410: return "Mukkir Masher";
                case 411: return "Harbinger's Bane";
                case 412: return "Master of the Elements";
                case 413: return "Killcrane's Ally";
                case 414: return "Apprentice Shadow Hunter";
                case 415: return "Squire of the Golden Flame";
                case 416: return "Knight of the Golden Flame";
                case 417: return "Knight of the Whispering Blade";
                case 418: return "The Black Spear";
                case 420: return "Carraida's Avenger";
                case 421: return "Paragon of the Whispering Blade";
                case 422: return "Paragon of the Rossu Morta";
                case 423: return "Chosen of Varicci";
                case 424: return "Chosen of Elysa";
                case 425: return "Small Mukkir Squasher";
                case 426: return "Blood Warrior";
                case 427: return "Strategist";
                case 428: return "War Beast";
                case 429: return "Champion of Daemal";
                case 430: return "Hero of the Golden Flame";
                case 431: return "Slayer of the Black Spear";
                case 433: return "Obviously Bored";
                case 434: return "Zefir Zapper";
                case 435: return "Tusker Blight";
                case 436: return "Elemental Eradicator";
                case 437: return "Expert Banished Hunter";
                case 438: return "Expert Fallen Hunter";
                case 439: return "Elite Head Hunter";
                case 440: return "Friend of the Frostglaive";
                case 441: return "Squire of New Viamont";
                case 442: return "Reanimator";
                case 443: return "Zombie Incursion Survivor";
                case 444: return "Ulgrim's Drinking Buddy";
                case 445: return "Master of the Porcelain Altar";
                case 446: return "Master of the Mystical Mug";
                case 447: return "Colosseum Champion";
                case 448: return "Titan";
                case 449: return "Colossus";
                case 450: return "Master Gladiator";
                case 451: return "Fearless";
                case 452: return "Lord of the Arena";
                case 453: return "Ring Master";
                case 454: return "Pit Fighter";
                case 455: return "Myrmidon";
                case 456: return "Hostile Combatant";
                case 457: return "Survivalist";
                case 458: return "Warrior of the Seventh Circle";
                case 459: return "Gladiator";
                case 460: return "Contender";
                case 461: return "Drudge Dread";
                case 462: return "Arena Custodian";
                case 463: return "Arena Rat";
                case 464: return "Scrapper";
                case 465: return "Champion of Stone";
                case 466: return "Champion of Sickles";
                case 467: return "Champion of the Wild";
                case 468: return "Champion of the Hive";
                case 469: return "Champion of Assassins";
                case 470: return "Immortal Champion";
                case 471: return "Ruuk Ally";
                case 472: return "Seeker of Asheron";
                case 473: return "Seeker of Torgluuk";
                case 474: return "Portal Ritualist";
                case 475: return "Ranger Ruuk";
                case 476: return "Basher Slasher";
                case 477: return "Guruk Hunter";
                case 478: return "Dead Eye for the Colossi";
                case 479: return "Fiendish Huntsman";
                case 480: return "Monster Killer";
                case 481: return "Bosh Bosh Kibosh";
                case 482: return "Mushroom Collector";
                case 483: return "Fungal Farmer";
                case 484: return "Mushroom Man";
                case 485: return "Fungi";
                case 486: return "Mushroom King";
                case 487: return "Thrungamandius";
                case 488: return "Initiate of the Blade";
                case 489: return "Torgluuk's Liberator";
                case 490: return "Burun Liberator";
                case 491: return "Asheron's Savior";
                case 492: return "Asheron's Defender";
                case 494: return "Fuzzy Bunny Slayer";
                case 495: return "Moar Hunter";
                case 496: return "Spiketooth Slayer";
                case 497: return "Tower Guardian Architect";
                case 498: return "Artisan of the Flame and Light";
                case 499: return "Guardian of the Tower";
                case 500: return "Cragstone Militia";
                case 501: return "Cragstone Knight";
                case 502: return "Guardian of Cragstone";
                case 503: return "Knight of the Windmill";
                case 504: return "Hero of House Mhoire";
                case 505: return "Lady Tairla's Champion";
                case 506: return "Royal Investigator";
                case 507: return "Wanga Fighter";
                case 508: return "Hoogan's Hero";
                case 509: return "Cragstone Firefighter";
                case 511: return "Stalker Stalker";
                case 512: return "Ravenous";
                case 513: return "Altered Hunter";
                case 514: return "Augmented Hunter";
                case 515: return "Drudge Doom";
                case 516: return "Defender of Kryst";
                case 517: return "Paradox-touched Queenslayer";
                case 518: return "Amelia's Caretaker";
                case 519: return "Prodigal Tusker Slayer";
                case 520: return "Mudmouth's Bane";
                case 521: return "Oolutanga's Bane";
                case 522: return "Prodigal Shadow Slayer";
                case 523: return "Prodigal Harbinger Slayer";
                case 524: return "Blood Seeker";
                case 525: return "Storm Rider";
                case 526: return "Meddler";
                case 527: return "Vile Betrayer";
                case 528: return "Spy";
                case 529: return "Slithis Slayer";
                case 530: return "Chosen of the Rift";
                case 531: return "Rift Shifter";
                case 532: return "Rift Walker";
                case 533: return "Reef Builder";
                case 534: return "Reef Breaker";
                case 535: return "Crypt Rat";
                case 536: return "Grave Stalker";
                case 537: return "Bone Breaker";
                case 538: return "Crypt Creeper";
                case 539: return "Tomb Raider";
                case 540: return "Follower of the Vine";
                case 541: return "Harvester";
                case 542: return "Harvester Harvester";
                case 543: return "Harvester Harvester Harvester";
                case 544: return "Pumpkin Throne Usurper";
                case 545: return "Death Knight";
                case 546: return "";
                case 547: return "Tracker Guardian";
                case 548: return "Dojiro Sangi's Savior";
                case 549: return "Master of the Hunt";
                case 550: return "Initiate of the Hunt";
                case 551: return "Apprentice of the Hunt";
                case 552: return "Disciple of the Hunt";
                case 553: return "Seeker of the Hunt";
                case 554: return "Champion of the Hunt";
                case 555: return "Guardian of Linvak Tukal";
                case 556: return "Unwitting Participant";
                case 557: return "Friend of Rheaga";
                case 558: return "Slayer of Rheaga";
                case 559: return "Protector of the Past";
                case 560: return "Warrior of the Past";
                case 561: return "Anthropologist";
                case 562: return "Gold Farmer";
                case 563: return "Third Eye Blinder";
                case 564: return "Dire Drudge Decapitator";
                case 565: return "Renegade Hunter";
                case 566: return "Banderling Bully";
                case 567: return "Xenophobic";
                case 568: return "Shadow Sunderer";
                case 569: return "Dire Huntsman";
                case 570: return "Game Warden";
                case 571: return "Honorary Rea of the Aun";
                case 572: return "Hope of the Past";
                case 573: return "Beacon of Hope";
                case 574: return "Aerbax's Bane";
                case 575: return "Aerbax Slayer";
                case 576: return "Jester's Emancipator";
                case 577: return "Jester's Fool";
                case 578: return "Jester's Accomplice";
                case 579: return "Honorary Burun Scout";
                case 580: return "Marble Wrangler";
                case 581: return "Secret Keeper";
                case 582: return "Jester's Little Helper";
                case 583: return "Hard to Kill";
                case 584: return "Expendable";
                case 585: return "Novice of the Sea";
                case 586: return "Acolyte of the Sea";
                case 587: return "Minister of the Sea";
                case 588: return "Defender of the Sea";
                case 589: return "Champion of the Sea";
                case 590: return "Master of the Sea";
                case 591: return "Defeater of the Blight";
                case 592: return "Champion of the Aerlinthe Node";
                case 593: return "Champion of the A'mun Node";
                case 594: return "Champion of the Esper Node";
                case 595: return "Champion of the Halaetan Node";
                case 596: return "Champion of the Linvak Node";
                case 597: return "Champion of the Obsidian Node";
                case 599: return "Ulgrim's Happy Hundredth";
                case 600: return "Plucker of Eyes";
                case 601: return "Warden of the Burning Wood";
                case 602: return "Tough Tough";
                case 603: return "Archaeologist";
                case 604: return "Hero of Woe";
                case 605: return "Defender of Silyun";
                case 606: return "Memorial Champion";
                case 607: return "Thane of Colier";
                case 608: return "Guardian of the Keep";
                case 609: return "Warrior of the Crater Lake";
                case 611: return "Arwician";
                case 612: return "Desert Warrior";
                case 613: return "Mayoi Protector";
                case 614: return "Stone Collector";
                case 615: return "Rock Star";
                case 616: return "Rock Hound";
                case 617: return "Warrior of Woe";
                case 618: return "Has way too much time";
                case 619: return "Champion Immemorial";
                case 620: return "Colier Miner";
                case 621: return "Legionnaire";
                case 622: return "Volcanologist";
                case 623: return "Hilltop Defender";
                case 624: return "Arwic Noble";
                case 625: return "Zharalim";
                case 626: return "Samurai";
                case 627: return "Guardian in the Patriarch Raids";
                case 628: return "Warden in the Patriarch Raids";
                case 629: return "Hero of the Patriarch Raids";
                case 630: return "Marked by the Patriarchs";
                case 637: return "Cathedrals Champion";
                case 638: return "Asheron's Militia";
                case 639: return "Minik Ra's Bane";
                case 640: return "Kazyk Ri's Bane";
                case 641: return "Nivinizk's Bane";
                case 642: return "Minik Ra's Nemesis";
                case 643: return "Kazyk Ri's Nemesis";
                case 644: return "Nivinizk's Nemesis";
                case 645: return "Auberean's Sentinel";
                case 646: return "Dereth's Elite";
                case 647: return "Defender of the Deru";
                case 648: return "Bane of the Blessed";
                case 649: return "Negotiator";
                case 650: return "Bane of the Blight";
                case 651: return "Gifted";
                case 652: return "Seasonal Seeker";
                case 653: return "Amateur Explorer";
                case 654: return "Experienced Explorer";
                case 655: return "Adept Explorer";
                case 656: return "Master Explorer";
                case 657: return "Elite Explorer";
                case 658: return "Mountain Climber";
                case 659: return "Daredevil";
                case 660: return "Sky Diver";
                case 661: return "Spelunker";
                case 662: return "Party-Goer";
                case 663: return "Crater Crasher";
                case 664: return "Tactical Aid";
                case 665: return "True Tactician";
                case 666: return "Tactical Fantastical";
                case 667: return "Fire of the Tanada";
                case 668: return "Crystalline Adventurer";
                case 669: return "Wisp Whipper";
                case 670: return "Burning Soul";
                case 671: return "Frozen Fighter";
                case 672: return "Dedicated";
                case 673: return "Assassin";
                case 674: return "Death Dealer";
                case 675: return "Bridge Jumper";
                case 676: return "Sure Step";
                case 677: return "Player Slayer";
                case 678: return "Bathed in Blood";
                case 679: return "I Am Darktide";
                case 680: return "Darkness in the Light";
                case 681: return "Beginning's End";
                case 682: return "Nexus Crawler";
                case 683: return "Selfless Soul";
                case 684: return "Timeless Adventurer";
                case 685: return "Virindi Informer";
                case 686: return "No Cage Can Hold Me";
                case 687: return "All for One";
                case 688: return "One for All";
                case 689: return "Jack-O'-All Trades";
                case 690: return "Knight of the Northeast Tower";
                case 691: return "Knight of the Northwest Tower";
                case 692: return "Knight of the Southeast Tower";
                case 693: return "Knight of the Southwest Tower";
                case 694: return "Knight of the Mhoire Throne";
                case 695: return "Historian of the Mhoire Throne";
                case 696: return "Champion of House Mhoire";
                case 697: return "Swordbearer of House Mhoire";
                case 698: return "Archmage of House Mhoire";
                case 699: return "Seeker of Castle Mhoire";
                case 700: return "Steward of Castle Mhoire";
                case 701: return "Golden Gear Crafter";
                case 702: return "Ally of the Gold Primus";
                case 703: return "Gear Knight Assassin";
                case 704: return "Gear Knight Recruiter";
                case 705: return "Gear Knight Emissary";
                case 706: return "Menhir Seeker";
                case 707: return "Mana Field Finder";
                case 708: return "Assistant's Assistant";
                case 709: return "Arcanum Adventurer";
                case 710: return "Gear Knight Defender";
                case 711: return "Soldier of the Queen";
                case 712: return "Spitter of the Queen";
                case 713: return "Bloodstone Hunter";
                case 714: return "Guiding Light";
                case 715: return "Clouded Soul";
                case 716: return "Undercover of Darkness";
                case 717: return "Brought to Light";
                case 719: return "Illuminating the Shadows";
                case 720: return "Exploring Archaeologist";
                case 721: return "Contract Killer";
                case 722: return "Shadow Puppet";
                case 723: return "Hopebringer";
                case 724: return "In the Dark";
                case 726: return "Searching the Shadows";
                case 727: return "Shadow Soldier";
                case 728: return "Bright Knight";
                case 729: return "Merciful Killer";
                case 730: return "Soul Siphon";
                case 731: return "The Tou-Tou Terror";
                case 732: return "Double Agent";
                case 733: return "Duleing with the Dark";
                case 734: return "Creature of Chaos";
                case 735: return "Conspirator";
                case 736: return "Hero of the Night";
                case 737: return "Master of the Twisted Word";
                case 738: return "The Nightmare Lord";
                case 739: return "The Nightmare Mage";
                case 740: return "The Twisted Weaver";
                case 741: return "Lord of Dark Dreams";
                case 743: return "The Dark Dreamwalker";
                case 745: return "The Dreamslayer";
                case 746: return "The Nightmare Stalker";
                case 748: return "The Thought Spiral";
                case 751: return "Master of the Oubliette";
                case 753: return "The Restless";
                case 754: return "Fiery Spirit";
                case 755: return "Icy Veins";
                case 756: return "Shocking Disposition";
                case 757: return "Acidic Soul";
                case 758: return "Grounded Morals";
                case 759: return "Darkened Heart";
                case 760: return "The True Emperor";
                case 761: return "Bearer of Darkness";
                case 763: return "Healer Ritualist";
                case 764: return "Vanquisher of the Titan";
                case 765: return "Derethian Newbie";
                case 766: return "Novice Wanderer";
                case 767: return "Notable Citizen";
                case 768: return "Adept Adventurer";
                case 769: return "Intrepid Explorer";
                case 770: return "Supreme Soldier";
                case 771: return "Epic Warrior";
                case 772: return "Paragon of New Aluvia";
                case 773: return "An Auberean Legend";
                case 774: return "Heretic";
                case 775: return "Captain";
                case 776: return "Pet Savior";
                case 777: return "Avalanche Avoider";
                case 778: return "Liberator of Uziz";
                case 779: return "Out of Tune";
                case 780: return "Hive Queenslayer";
                case 781: return "Eviscerator Decimator";
                case 782: return "Ultimate Warrior";
                case 783: return "Stone Cold Killer";
                case 784: return "Queller of Rage";
                case 785: return "Ender of Torment";
                case 786: return "Controller of Emotions";
                case 787: return "Rynthid Ravager";
                case 788: return "Lothus Servitor";
                case 789: return "Ally of the Lothus";
                case 790: return "Ally of the Council";
                case 791: return "Emotional Wreck";
                case 792: return "Minion Marauder";
                case 793: return "Rynthid Wrecker";
                case 794: return "Mender of the Rift";
                case 795: return "Rage Quitter";
                case 796: return "Sorcerer Slayer";
                case 797: return "Night Owl";
                case 798: return "Purifier";
                case 799: return "Fan of Asheron";
                case 800: return "Asheron's #1 Fan";
                case 801: return "Shutterbug";
                case 802: return "The Focused";
                case 803: return "Dereth Recruiter";
                case 804: return "Fowl Follower";
                case 805: return "Follower of Asheron";
                case 806: return "Follows Directions";
                case 807: return "Can't Follow Directions";
                case 808: return "Likes Asheron";
                case 809: return "Likes Getting Titles";
                case 810: return "Likes Where This Is Going";
                case 811: return "Likes Ulgrim";
                case 812: return "Likable";
                case 813: return "Captivating";
                case 814: return "Master of Ceremony";
                case 815: return "Road Warrior";
                case 816: return "Thriller";
                case 817: return "Haunts Your Dreams";
                case 818: return "Asheron's Collect Caller";
                case 819: return "The Inquisitive";
                case 820: return "Portal Stormer";
                case 821: return "Bringer of Pain";
                case 822: return "Harbinger of Madness";
                case 823: return "Marked by Luck";
                case 824: return "Marked by Fate";
                case 825: return "Marked by Fame";
                case 826: return "Marked by Glamour";
                case 827: return "Marked by Bacon";
                case 828: return "Puzzlemaster";
                case 829: return "Riddle Ravager";
                case 830: return "The Cool Kids Club";
                case 831: return "Epic Win";
                case 832: return "Epic Fail";
                case 833: return "Always Picked First";
                case 834: return "Always Picked Last";
                case 835: return "Forever Alone";
                case 836: return "99 Problems, Olthoi Ate 1";
                case 837: return "Hungry for Moar";
                case 838: return "I Can Haz Title Nao";
                case 839: return "Snowbunny";
                case 840: return "Cold as Ice";
                case 841: return "Penguin Plunge";
                case 842: return "Flower Sniffer";
                case 843: return "Springs Into Action";
                case 844: return "Heats Things Up";
                case 845: return "Cruel Summer";
                case 846: return "Hot in the City";
                case 847: return "Runs Through Sprinklers";
                case 848: return "The Knowledgeable";
                case 849: return "Well Trained";
                case 850: return "Pumpkin Lord";
                case 851: return "Haunted";
                case 852: return "Possessed";
                case 853: return "Doomsayer";
                case 854: return "Accursed";
                case 855: return "Cold Turkey";
                case 856: return "Jive Turkey";
                case 857: return "Present Protector";
                case 858: return "Holly Jolly Helper";
                case 859: return "Loss Prevention";
                case 860: return "Gift Gopher";
                case 861: return "Holiday Hero";
                case 862: return "Crown Of the Deru";
                case 863: return "Viridian Dreamer";
                case 864: return "Viridian Lord";
                case 865: return "Viridian Knight";
                case 866: return "Viridian Stalker";
                case 867: return "Viridian Slayer";
                case 868: return "Viridian Purifier";
                case 869: return "Knight Of Thorns";
                case 870: return "Hunter Of Thorns";
                case 871: return "Mage Of Thorns";
                case 872: return "Thornstalker";
                case 873: return "Champion Of The Viridian Tree";
                case 874: return "Corruptor Of The Root";
                case 875: return "Killer Among Shadows";
                case 876: return "Servant Of The Vile";
                case 877: return "Knight Of Corrupted Amber";
                case 878: return "Gauntlet Champion";
                case 879: return "Bloodthirsty";
                case 880: return "Gauntlet Gladiator";
                case 881: return "Wily Warrior";
                case 882: return "Soldier of Fortune";
                case 883: return "Society Savage";
                case 884: return "Coin Collector";
                case 885: return "Brutal Barbarian";
                case 886: return "Idolized";
                case 887: return "Master of Puppets";
                case 888: return "Titan Slayer";
                case 889: return "Awakened";
                case 890: return "Enlightened";
                case 891: return "Illuminated";
                case 892: return "Transcended";
                case 893: return "Cosmic Conscious";
                case 894: return "Last Man Standing";
                default: return "";
            }
        }
    }
}
